# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 626bf631f4ddc9516e5f5dbefeea46fc146acf2f1487b12b2801de485ecd50675f3022459b1dd3421572bcedbc8e14a362b930f0e054bd78776c7dafab3d74d4

test:
  secret_key_base: 5468df32262af7ab9fd27c58ceef240bd57c1f02f247871ca29384b35e46eb3c49fb4674b6f47b0afc6479038b226008a544ea001eb2d6866ad187f0570b491e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
